### ISSUE TITLE
New 2.6.1 version AttributeError: 'Parallel' object has no attribute '__process_manager'

### ISSUE THREAD

**Issue by KennLu2914** [Ecogenomics/GTDBTk#683]
Hi Pierre, 

Just updated to the new 2.6.1 version (installed by mamba), had a successful run on the first download, then it keeps going into the following error message on aqua server: 

[2025-12-22 00:43:40] INFO: Using GTDB-Tk reference data version r226: /work/WISE_microbes/db/gtdb/release226/
[2025-12-22 00:43:40] INFO: Identifying markers in 58 genomes with 1 threads.
[2025-12-22 00:43:40] TASK: Running Prodigal V2.6.3 to identify genes.
==> Processed 0/58 genomes (0%) |               | [?genome/s, ETA ?]Traceback (most recent call last):
  File "/mnt/hpccs01/work/WISE_microbes/miniforge3/envs/gtdbtk/lib/python3.14/multiprocessing/forkserver.py", line 340, in main
    code = _serve_one(child_r, fds,
                      unused_fds,
                      old_handlers)
  File "/mnt/hpccs01/work/WISE_microbes/miniforge3/envs/gtdbtk/lib/python3.14/multiprocessing/forkserver.py", line 380, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/mnt/hpccs01/work/WISE_microbes/miniforge3/envs/gtdbtk/lib/python3.14/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'Parallel' object has no attribute '__process_manager'

Tried to update mamba and all packages.

## Server information
- CPU: `grep -m 1 "^model name" /proc/cpuinfo && grep -c "^processor" /proc/cpuinfo`
- model name	: AMD EPYC 9684X 96-Core Processor
384

Thank you

**Comment by ruben1294** [comment]
Hello, I had exactly the same error. Same version of python as well (3.14). From what I looked, it seems like python 3.14 is incompatible with GTDB-Tk 2.6.1, as it's very recent. You could try with an older version of python, I will try that in the next few weeks and see if that solves the issue. If you happen to try that, please let us know as well.

Some threads with similar issues that point to issues with parallel job of python 3.1X:

https://github.com/joblib/joblib/issues/1544
https://github.com/pydantic/pydantic/issues/12618

Kind regards,
Rubén

**Comment by Jiung-Wen** [comment]
I ran into the same issue and solved it by pinning Python to version 3.12.
`mamba create -n gtdbtk-2.6.1 -c conda-forge -c bioconda gtdbtk=2.6.1 python=3.12`
I haven't tested this with Python 3.13, as 3.12 worked for me. I hope this helps.

**Comment by KennLu2914** [comment]
Thanks @ruben1294  @Jiung-Wen, that works perfectly with Python 3.12. 

Cheers

**Comment by fplazaonate** [comment]
It works with Python 3.13 as well.
I will update the bioconda recipe accordingly.

**Comment by fplazaonate** [comment]
It is fixed with the new bioconda recipe.
GTDB-tk is now installed with Python < 3.14

**Comment by enzovalentino** [comment]
Hi everyone, I'm having the same error. 
I'm working on a Mac Pro (Apple Silicon chip), and I've created a conda environment with these steps: 

```
conda create -n gtdbtk-2.6.1 -c conda-forge -c bioconda --platform osx-64 python=3.12
conda activate gtdbtk-2.6.1
conda install -c bioconda hmmer==3.4
conda install -c bioconda prodigal==2.6.2
conda install -c bioconda pplacer # (1.1.alpha17)
conda install -c bioconda skani==0.3.1 # con le versioni 0.2.1 e 0.2.2 mi usciva un errore
conda install -c bioconda fasttree==2.2.0
pip install gtdbtk==2.6.1
```

However, when prodigal starts, I have this message: 
```
==> Processed 0/415 genomes (0%) |               | [?genome/s, ETA ?]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gtdbtk-2.6.1/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/gtdbtk-2.6.1/lib/python3.12/multiprocessing/spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Parallel' object has no attribute '__process_manager'
```

I've already tried to down/upgrade python. 

Thank you
